### Get all TodoItems
GET http://localhost:8080/restapi/TodoItems

### Get a single TodoItem with an id of 1
GET http://localhost:8080/restapi/TodoItems/1

### POST a new TodoItem with valid data
POST http://localhost:8080/restapi/TodoItems
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJEQVVTVElOIiwidXBuIjoiREFVU1RJTiIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJJVCJdLCJqdGkiOiI4OTc2MDhmYS0wNjdkLTRhMzQtODZmMy1lZmEwZDFmYWZlOGMiLCJpYXQiOjE2ODE3NzU1ODAsImV4cCI6MTY4MTc4OTk4MH0.i3pTKPGN5j1Bkm_whFgo8Ybq-7_ZV6JKKNqvkj16zMGcv21QB4NVD3mxheVr-n3XAEt2YtYIYhCYbQSS2drvJBeW_EsF74LRnoHCtcpYyFndd6ID0WcJmg20-rf-O0RxIhzzz5aiPFt8CoE7Tq4xr5_sdVdJ00MzI7V8AilcDN0LZyVDtBqhZYfH2yZhIUoJ6VC53P56BJh3wbWiK-K9qK5WW8tBH-Ht_ALRX1QU5O7jjC2UfJT1GEYBsExIsDL1iFca9l5OI3HLKuPegQd1ASKfSeYJrxNMTYgTYJagHGqKI4Udq52udjH7KtyqjFwMe7eANId6paFB4fS_n-AT5w

{
  "name": "Start DMIT2015 Assignment 3",
  "complete": false
}

### Post a new TodoItem with invalid data
POST http://localhost:8080/restapi/TodoItems
Content-Type: application/json

{
  "name": "     ",
  "complete": false
}

### Get a single TodoItem with an id of 4
GET http://localhost:8080/restapi/TodoItems/4

### Update TodoItem with an id of 4 with valid data
PUT http://localhost:8080/restapi/TodoItems/4
Content-Type: application/json

{
  "id": 4,
  "name": "Commit DMIT2015 Assignment 3",
  "complete": true,
  "version": 0
}

### Delete an TodoItem with an id of 2
DELETE http://localhost:8080/restapi/TodoItems/2

### Delete an TodoItem with an id of 4
DELETE http://localhost:8080/restapi/TodoItems/4
Authorization:  bearer eyJraWQiOiJxdWlja3N0YXJ0LWp3dC1pc3N1ZXIiLCJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJEQVVTVElOIiwidXBuIjoiREFVU1RJTiIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJJVCJdLCJqdGkiOiI4OTc2MDhmYS0wNjdkLTRhMzQtODZmMy1lZmEwZDFmYWZlOGMiLCJpYXQiOjE2ODE3NzU1ODAsImV4cCI6MTY4MTc4OTk4MH0.i3pTKPGN5j1Bkm_whFgo8Ybq-7_ZV6JKKNqvkj16zMGcv21QB4NVD3mxheVr-n3XAEt2YtYIYhCYbQSS2drvJBeW_EsF74LRnoHCtcpYyFndd6ID0WcJmg20-rf-O0RxIhzzz5aiPFt8CoE7Tq4xr5_sdVdJ00MzI7V8AilcDN0LZyVDtBqhZYfH2yZhIUoJ6VC53P56BJh3wbWiK-K9qK5WW8tBH-Ht_ALRX1QU5O7jjC2UfJT1GEYBsExIsDL1iFca9l5OI3HLKuPegQd1ASKfSeYJrxNMTYgTYJagHGqKI4Udq52udjH7KtyqjFwMe7eANId6paFB4fS_n-AT5w